name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: notify
          POSTGRES_PASSWORD: notify
          POSTGRES_DB: notify_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Test with pytest
        run: pytest --cov=.
        env:
          REDIS_STREAM_HOST: localhost
          HDX_NOTIFICATIONSDB_ADDR: localhost
          HDX_NOTIFICATIONSDB_PORT: 5432
          HDX_NOTIFICATIONSDB_USER: notify
          HDX_NOTIFICATIONSDB_PASS: notify
          HDX_NOTIFICATIONSDB_DB: notify_test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
